create table IF NOT EXISTS users (
    id bigint generated by default as identity,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    start_of_work date not null,
    primary key (id),
    unique (first_name, last_name, start_of_work)
);