services:
  dev-postgres:
    image: postgres
    container_name: dev-postgres
    ports:
      - "45533:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_mem
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  budget-service:
    build: .
    container_name: budget-service
    ports:
      - "8080:8080"
    depends_on:
      - dev-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dev-postgres:5432/dev_mem
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev

volumes:
  postgres-data: