create table budget (
        id bigint generated by default as identity PRIMARY KEY,
        month integer not null,
        year integer not null,
        amount integer not null,
        budget_type varchar(255) check (budget_type in ('credit','debit'))
    )