CREATE TABLE author (
    id bigint generated by default as identity,
    fio varchar(255),
    create_data timestamp(6),
    primary key (id)
);

CREATE TABLE temp_budget (
    id bigint generated by default as identity PRIMARY KEY,
    month integer,
    year integer,
    amount integer,
    budget_type varchar(255),
    author_id bigint,
    create_record timestamp(6)
);

INSERT INTO temp_budget (id, month, year, amount, budget_type, author_id, create_record)
SELECT
    b.id,
    b.month,
    b.year,
    b.amount,
    b.budget_type,
    NULL::bigint,
    NULL::timestamp(6)
FROM budget b;

DROP TABLE budget;

ALTER TABLE temp_budget RENAME TO budget;

ALTER TABLE budget
ADD CONSTRAINT budget_type_check
CHECK (budget_type in ('credit','debit'));

ALTER TABLE budget
ALTER COLUMN amount SET NOT NULL;

ALTER TABLE budget
ALTER COLUMN month SET NOT NULL;

ALTER TABLE budget
ALTER COLUMN year SET NOT NULL;

ALTER TABLE budget
ALTER COLUMN budget_type SET NOT NULL;

ALTER TABLE budget
ADD FOREIGN KEY (author_id) REFERENCES author(id);