CREATE TABLE author (
    id bigint generated by default as identity,
    fio varchar(255),
    create_data timestamp(6),
    primary key (id)
);

CREATE TABLE temp_budget (
    id bigint generated by default as identity PRIMARY KEY,
    mount integer,
    year integer,
    amount integer,
    budget_type varchar(255),
    author_id bigint
);

INSERT INTO temp_budget (id, mount, year, amount, budget_type, author_id)
SELECT
    b.id,
    b.mount,
    b.year,
    b.amount,
    b.budget_type,
    NULL::bigint
FROM budget b;

DROP TABLE budget;

ALTER TABLE temp_budget RENAME TO budget;

ALTER TABLE budget
ADD CONSTRAINT budget_type_check
CHECK (budget_type in ('credit','debit'));

ALTER TABLE budget
ALTER COLUMN amount SET NOT NULL;

ALTER TABLE budget
ALTER COLUMN mount SET NOT NULL;

ALTER TABLE budget
ALTER COLUMN year SET NOT NULL;

ALTER TABLE budget
ALTER COLUMN budget_type SET NOT NULL;

ALTER TABLE budget
ADD FOREIGN KEY (author_id) REFERENCES author(id);